remoteNamespace: "travix-dev"
namespace: default
replicaCount: 1
image:
  repository: allloush92/chaos_monkey
  pullPolicy: IfNotPresent
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false

role:
  name: pods-controller
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole

roleBinding:
  name: pods-controller-binding

chaosMonkeyRate: "1"