apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  selector:
    matchLabels:
      app: chaos-monkey-app
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
        app: chaos-monkey-app
    spec:
      containers:
        - name: chaos-monkey-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: namespace
              value: {{ .Values.remoteNamespace }}
            - name: rate
              value: "{{ .Values.chaosMonkeyRate }}"