apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.roleBinding.name }}
  namespace: {{ .Values.remoteNamespace }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.namespace }}
roleRef:
  kind: {{ .Values.role.kind }}
  name: {{ .Values.role.name }}
  apiGroup: {{ .Values.role.apiGroup }}