kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.role.name }}
  namespace: {{ .Values.remoteNamespace }}
rules:
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["list","get","delete"]